---
- name: '[Debian] Include all Debian-specific variables'
  include_vars: Debian.yml
  tags:
    - mpd

# To do something only if some distro installed on the host
# Even specific distro version can be specified, see:
# https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html
# example:
#     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
#
# ansible_distribuion: ['MacOSX', 'Debian', 'Ubuntu', 'CentOS', 'Red Hat Enterprise Linux', 'Windows 10']
# ansible_os_family: ['Darwin', 'Debian', 'Debian' 'RedHat', 'RedHat' 'Windows']
#
- name: '[Debian] Install mpd package'
  action: >
    {{ ansible_pkg_mgr }} name=mpd state=latest update_cache=yes
  become: yes
  tags:
    - mpd

- name: '[Debian] Install mpc package'
  action: >
    {{ ansible_pkg_mgr }} name=mpc state=latest update_cache=yes
  become: yes
  when: mpd_install_mpc
  tags:
    - mpd
    - mpc

- name: '[Debian] Install ncmpcpp package'
  action: >
    {{ ansible_pkg_mgr }} name=ncmpcpp state=latest update_cache=yes
  become: yes
  when: mpd_install_ncmpcpp
  tags:
    - mpd
    - ncmpcpp

- name: '[Debian] Enable and Start mpd service if needed'
  service:
    name: mpd
    enabled: "{{ mpd_autostart }}"
    state: "{% if mpd_autostart %}started{% else %}stopped{% endif %}"
  become: yes
  tags:
    - mpd

- name: '[Debian] Enable mpd socket if needed'
  service:
    name: mpd.socket
    enabled: "{% if mpd_autostart %}no{% else %}yes{% endif %}"
    state: "{% if mpd_autostart %}stopped{% else %}started{% endif %}"
  become: yes
  tags:
    - mpd

- name: '[Debian] Generate mpd.conf from template'
  template: src=mpd.conf.j2 dest=/etc/mpd.conf backup=yes owner=root group=root mode=0644
  notify: Restart mpd service
  become: yes
  tags:
    - mpd

- name: '[Debian] Create ~/.ncmpcpp folder for each mpd_ncmpcpp_user'
  file: path='~/.ncmpcpp' state=directory owner="{{ item }}" group="{{ item }}" mode=0755
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ mpd_ncmpcpp_users }}"
  when:
    - mpd_install_ncmpcpp
    - mpd_ncmpcpp_users is defined
    - mpd_ncmpcpp_users | length > 0
  tags:
    - mpd
    - ncmpcpp

- name: '[Debian] Generate ncmpcpp config from template'
  template: src=ncmpcpp.conf.j2 dest='~/.ncmpcpp/config' owner="{{ item }}" group="{{ item }}" mode=0644
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ mpd_ncmpcpp_users }}"
  when:
    - mpd_install_ncmpcpp
    - mpd_ncmpcpp_users is defined
    - mpd_ncmpcpp_users | length > 0
  tags:
    - mpd
    - ncmpcpp

- stat: path=/usr/sbin/firewalld
  register: mpd_stat_1_firewalld
  tags:
    - mpd

- stat: path=/sbin/firewalld
  register: mpd_stat_2_firewalld
  tags:
    - mpd

- name: '[Debian] Open mpd port in firewall'
  firewalld: port="{{ mpd_port }}/tcp" zone="{{ item }}" permanent=true immediate=yes state=enabled
  with_items: "{{ mpd_firewall_zones }}"
  become: yes
  when: mpd_stat_1_firewalld.stat.exists or mpd_stat_2_firewalld.stat.exists
  tags:
    - mpd
...
