- import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: ms_mpd_enabled|bool
  tags:
    - setup-all
    - setup-ms-mpd

- import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: not ms_mpd_enabled|bool
  tags:
    - setup-all
    - setup-ms-mpd
