---
# tasks file for mpd

- name: "[main] Include {{ ansible_os_family }}-specific tasks"
  include_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - mpd
    - mpc
    - ncmpcpp

- meta: flush_handlers
  tags:
    - mpd
...
