---
# handlers file for mpd

# Linux services:
- name: Restart mpd service
  service:
    name: mpd
    state: restarted
    enabled: yes
  when: mpd_autostart
  become: yes


### MACOS
# Brew services:
- name: Restart mpd service with brew services command
  command: /usr/local/bin/brew services restart mpd
  when: mpd_autostart
  become: no
...
